"""create project table

Revision ID: 46042f26b666
Revises: 7b1cf6fca5c2
Create Date: 2026-07-16 09:01:27.175971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46042f26b666'
down_revision = '7b1cf6fca5c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
