"""initial

Revision ID: 7b1cf6fca5c2
Revises: a337deaa0ad0
Create Date: 2026-07-16 08:48:23.208950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1cf6fca5c2'
down_revision = 'a337deaa0ad0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
