"""create project table

Revision ID: 9dab418ee283
Revises: 46042f26b666
Create Date: 2026-07-16 09:07:22.591213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dab418ee283'
down_revision = '46042f26b666'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
