"""initial

Revision ID: a337deaa0ad0
Revises: fdbd68d0a4ed
Create Date: 2026-07-15 21:12:46.769789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a337deaa0ad0'
down_revision = 'fdbd68d0a4ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
